name: Build Millennium

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Visual Studio 2022
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17'

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.21.1'

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
      shell: pwsh

    - name: Set VCPKG_ROOT environment variable
      run: echo "VCPKG_ROOT=$PWD/vcpkg" >> $GITHUB_ENV
      shell: pwsh

    - name: Verify VCPKG_ROOT
      run: |
        echo $env:VCPKG_ROOT
        echo $env:VCPKG_ROOT
      shell: pwsh

    - name: Configure CMake
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        cmake --preset=actions-windows-x86

    - name: Build
      run: |
        cmake --build build --config Release