name: Build Millennium

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Visual Studio 2022
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17'

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.21.1'

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install

    - name: Set vcpkg environment variables
      run: |
        echo "VCPKG_ROOT=$PWD/vcpkg" >> $GITHUB_ENV
        echo "$PWD/vcpkg" >> $GITHUB_PATH
        echo "VCPKG_ROOT directory -> $VCPKG_ROOT"

    - name: Configure CMake
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        cmake -S . -B build

    - name: Build
      run: |
        cmake --build build --config Release