#i was on the verge of killing myself while writing this build script (they have my family please help)
name: Build Installer

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # allow fortnite wallhacks 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MSVC
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Download and install Vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe integrate install
        working-directory: ${{ github.workspace }}

      - name: Install Vcpkg dependencies
        run: |
          ${{ github.workspace }}/vcpkg/vcpkg.exe install nlohmann-json:x86-windows

      - name: Build Installer
        run: |
          msbuild /p:Configuration=Release /p:Platform=x86 /m installer.sln
        working-directory: ${{ github.workspace }}

      - name: Set MSBuild path
        run: |
          echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_PATH
        shell: cmd

      - name: Calculate SHA-256 Hash
        run: |
          hash=$(sha256sum ${{ github.workspace }}/dist/installer-prod.Release-x86Windows/millennium.exe | cut -d ' ' -f 1)
          echo "::set-output name=hash::$hash"

      - name: Create Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ${{ github.workspace }}/dist/installer-prod.Release-x86Windows/millennium.exe  # Use the new build path
