name: Build Millennium (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: (Generator) Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.21.1'

    - name: (Dependency) Install vcpkg
      run: |
        # clone vcpkg to 
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        # bootstrap and install vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
      shell: pwsh

    - name: (Generator) Configure CMake
      run: |
        cmake --preset=actions-linux -DGITHUB_ACTION_BUILD=ON

    - name: Build Millennium
      run: |
        cmake --build build --config Release

        # Move the python311.dll binary to the release directory
        # move D:\a\Millennium\Millennium\Python-3.11.8\PCbuild\win32\python311.dll D:\a\Millennium\Millennium\build\Release\python311.dll

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: millennium
        path: D:/a/Millennium/Millennium/build/Release
