name: Build Millennium (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: (Generator) Setup Minimal MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Set up cache for Python source
      uses: actions/cache@v3
      id: build-cache
      with:
        path: |
          Python-3.11.8/PCbuild/win32
        key: ${{ runner.os }}-python-3.11.8-build
        restore-keys: |
          ${{ runner.os }}-python-3.11.8-build-  

    - name: (Python) Download 3.11.8 win32 source
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: |

        # download python 3.11.8 source code
        curl -o Python-3.11.8.tgz https://www.python.org/ftp/python/3.11.8/Python-3.11.8.tgz
        # extract the tarball
        tar -xzvf Python-3.11.8.tgz >nul 2>&1
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: (Python) Stage Python 3.11.8 static build
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: |
        cd Python-3.11.8

        $vcxprojPath = "PCbuild/pythoncore.vcxproj"
        $content = Get-Content $vcxprojPath -Raw  # Read the entire content as a single string

        $pattern = '</ClCompile>'
        $replacement = @"
        <RuntimeLibrary Condition="'`$(Configuration)|`$(Platform)'=='Release|Win32'">MultiThreaded</RuntimeLibrary>
        <RuntimeLibrary Condition="'`$(Configuration)|`$(Platform)'=='Debug|Win32'">MultiThreadedDebug</RuntimeLibrary>
        </ClCompile>
        "@

        $modifiedContent = $content -replace [regex]::Escape($pattern), $replacement
        $modifiedContent | Set-Content $vcxprojPath

      shell: pwsh

    - name: (Python) Build 3.11.8
      if: steps.build-cache.outputs.cache-hit != 'true'
      run: |

        cd Python-3.11.8
        # get python external libs before build
        ./PCbuild/get_externals.bat
        # build python 3.11.8 as win32 and release
        msbuild PCBuild/pcbuild.sln /p:Configuration=Release /p:Platform=Win32 /p:RuntimeLibrary=MT
        # verify python is installed
        PCbuild\win32\python.exe --version

    - name: (Generator) Integrate VS2022
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '17'
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: (Generator) Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.21.1'
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: (Dependency) Install vcpkg
      run: |

        # clone vcpkg to 
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        # bootstrap and install vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
      shell: pwsh
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: (Generator) Configure CMake
      run: |

        # set vs variables for cache generation
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        # generate cache for x86/win32 with vs 
        # - actions-windows-x86 @ CMakeUserPresets.json
        # - GITHUB_ACTION_BUILD (boolean) is a macro to help set include paths in CMakeLists.txt
        cmake --preset=actions-windows-x86 -G "Visual Studio 17 2022" -A Win32 -DGITHUB_ACTION_BUILD=ON
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Build Millennium
      run: |

        tree "D:\a\Millennium\Millennium"

        # build millennium with msvc; x86; release
        cmake --build build --config Release

        # Move the python311.dll binary to the release directory
        move D:\a\Millennium\Millennium\Python-3.11.8\PCbuild\win32\python311.dll D:\a\Millennium\Millennium\build\Release\python311.dll
      env: 
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: millennium
        path: D:/a/Millennium/Millennium/build/Release