name: Build Millennium

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MSVC
      uses: microsoft/setup-msbuild@v1.0.0


    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install required packages with vcpkg
      run: |
        .\vcpkg\vcpkg install nlohmann-json:x86-windows websocketpp:x86-windows


    - name: Set MSBuild path
      run: |
        echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_PATH 
        shell: cmd

    - name: Build project
      run: |
        msbuild millennium.sln /p:Configuration=Release /p:Platform=x86