name: Build Millennium

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MSVC
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Download and install Vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe integrate install
        working-directory: ${{ github.workspace }}

      - name: Install Vcpkg dependencies
        run: |
          .\vcpkg.exe install boost:x86-windows
          .\vcpkg.exe install cpp-netlib:x86-windows
          .\vcpkg.exe install rapidjson:x86-windows
          .\vcpkg.exe install nlohmann-json:x86-windows
          .\vcpkg.exe install websocketpp:x86-windows
        working-directory: ${{ github.workspace }}

      - name: Build Millennium
        run: |
          msbuild /p:Configuration=Release /p:Platform=x86 /m millennium.sln
        working-directory: ${{ github.workspace }}

      - name: Set MSBuild path
        run: |
          echo "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin" >> $GITHUB_PATH
        shell: cmd